// @ts-nocheck
/* Pure training domain logic, separated from the UI. */
const SportCore = (() => {
const START='2026-10-06';
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const pace=s=>`${Math.floor(Math.round(s)/60)}:${String(Math.round(s)%60).padStart(2,'0')}`;
const time=s=>`${Math.floor(Math.round(s)/60)}’${String(Math.round(s)%60).padStart(2,'0')}`;
const paces={EF:[345,390],'5k':[248,258],'10k':[265,275],'21k':[280,295],'42k':[295,310],recovery:[360,420],slow:[420,600],strides:[250,285]};
function step(seconds,zone,type='training',extra={}){return {seconds,zone,type,...extra}}
function easy(min){return {name:'Endurance fondamentale',kind:'easy',declared:min,steps:[step(min*60,'EF')],source:`${min} min EF`,note:'Conversation facile. Ralentis si nécessaire : le ressenti prime sur la fourchette d’allure.'}}
function interval(warm,reps,effort,zone,rec,cool,declared){let steps=[step(warm*60,'EF','warmup')];for(let i=0;i<reps;i++){steps.push(step(effort*60,zone));if(i<reps-1)steps.push(step(rec*60,'recovery','recovery'))}steps.push(step(cool*60,'EF','cooldown'));return {name:`${reps} × ${effort} min · allure ${zone.replace('k',' km')}`,kind:zone==='42k'||zone==='21k'?'long':'interval',declared,steps,source:`${warm} min EF + ${reps} × ${effort} min ${zone} / récupération ${rec} min EF + ${cool} min EF`,note:'Récupération entre les répétitions, sans récupération supplémentaire après la dernière. Allures initiales provisoires, à vérifier avec le ressenti.'}}
function hills(warm,reps,seconds,cool,declared){let steps=[step(warm*60,'EF','warmup')];for(let i=0;i<reps;i++){steps.push(step(seconds,'strides'));if(i<reps-1)steps.push(step(seconds===10?150:90,'slow','recovery'))}steps.push(step(cool*60,'EF','cooldown'));return {name:`${reps} × ${seconds} s · côtes / alternative plat`,kind:'strides',declared,steps,source:`${warm} min EF + ${reps} × ${seconds} s en côte + ${cool} min EF`,note:seconds===10?'Sans côte : accélérations progressives et relâchées sur plat, sans sprint maximal. Ce remplacement n’est pas équivalent aux côtes. Ne poursuis pas en cas de douleur.':'Sans côte : répétitions contrôlées sur plat à effort proche de l’allure 5 km, sans sprint. Le PDF prévoit une récupération en descente ; les 90 s sur plat sont une hypothèse à ajuster.',adaptation:true}}
function strides(warm,cool,declared,reps=8){return {...hills(warm,reps,20,cool,declared),name:`${reps} × 100 m progressifs`,source:`${warm} min EF + ${reps} × 100 m progressifs + ${cool} min EF`,steps:[step(warm*60,'EF','warmup'),...Array.from({length:reps},(_,i)=>[step(0,'strides','training',{meters:100}),...(i<reps-1?[step(60,'slow','recovery')]:[])]).flat(),step(cool*60,'EF','cooldown')],note:'100 m en accélération progressive, relâchée. Le PDF ne fixe pas la récupération : 60 s faciles sont une hypothèse visible à valider.',adaptation:true}}
function progressive(min,tempo){return {name:'Sortie longue progressive',kind:'long',declared:min+tempo+5,source:`${min} min EF + ${tempo} min progressives marathon → 10 km + 5 min EF`,steps:[step(min*60,'EF'),step(tempo*60/3,'42k'),step(tempo*60/3,'21k'),step(tempo*60/3,'10k'),step(300,'EF','cooldown')],note:'Répartition du bloc progressif en trois tiers, hypothèse de l’app. En cas de fatigue, conserve une allure facile : ne force pas le dernier tiers.',adaptation:true}}
const specs=[
[easy(40),interval(20,8,1.5,'5k',1.5,5,50),easy(40),hills(20,6,10,5,40),interval(30,4,5,'42k',3,10,65)],
[easy(45),interval(20,10,1.5,'5k',1.5,5,55),easy(40),hills(20,8,10,5,45),interval(30,4,6,'42k',2,10,70)],
[easy(50),interval(20,12,1.5,'5k',1.5,5,60),easy(40),hills(20,10,10,5,50),interval(45,3,8,'42k',2,5,80)],
[easy(30),interval(15,5,2,'10k',1,5,40),easy(40),strides(30,5,40),easy(60)],
[easy(45),interval(20,5,4,'10k',1.5,5,50),easy(40),hills(30,10,30,5,50),interval(40,4,5,'21k',2,10,75)],
[easy(45),interval(20,5,5,'10k',2,5,55),easy(40),hills(20,12,30,5,45),interval(30,4,6,'21k',2,15,75)],
[easy(45),interval(15,5,6,'10k',2,5,60),easy(40),hills(20,14,30,5,50),interval(30,4,7,'21k',2,15,80)],
[easy(40),interval(15,5,2,'10k',1,10,40),easy(40),strides(30,5,40),easy(70)],
[easy(45),interval(20,4,7,'10k',2,5,60),easy(40),hills(30,8,45,5,50),progressive(60,15)],
[easy(45),interval(15,4,8,'10k',2,5,60),easy(45),hills(20,10,45,5,45),progressive(60,20)],
[easy(40),interval(20,2,12,'10k',2,10,60),easy(30),{...easy(25),note:'Le PDF propose 5–6 × 100 m en option. Footing seul par défaut.'},interval(15,5,3,'10k',3,5,50)],
[easy(30),{name:'Repos',kind:'rest',declared:0,steps:[],source:'Repos'},interval(15,5,1,'10k',1,5,30),strides(20,0,25,6),{name:'10 km · jour de course',kind:'race',declared:0,steps:[step(0,'10k','training',{meters:10000})],source:'10 km. Échauffement non précisé dans le PDF.',note:'Date de fin du programme, pas une inscription à une course confirmée.'}]
];
function duration(s,ranges=paces){return s.steps.reduce((a,x)=>a+(x.meters?x.meters/1000*(ranges[x.zone][0]+ranges[x.zone][1])/2:x.seconds),0)}
function distance(s,ranges=paces){return s.steps.reduce((a,x)=>a+(x.meters?x.meters/1000:x.seconds/((ranges[x.zone][0]+ranges[x.zone][1])/2)),0)}
function plan(){return specs.flatMap((week,w)=>week.map((s,j)=>({...structuredClone(s),id:`w${w+1}-${j}`,week:w+1,date:addDays(START,w*7+[0,1,2,4,5][j]),phase:[4,8].includes(w+1)?'Assimilation':w>=10?'Affûtage':'Construction'})))}
function firstWeekCurrent(plan){return plan.map(s=>{if(s.week!==1)return s; if(s.date==='2026-10-06')return {...structuredClone(plan.find(x=>x.id==='w1-1')),id:s.id,date:s.date,corosId:'2',alreadyScheduled:true,steps:[step(1200,'EF','warmup'),...Array.from({length:8},()=>[step(90,'5k'),step(90,'recovery','recovery')]).flat(),step(300,'EF','cooldown')],note:'Ordre COROS conservé à ta demande : fractionné mardi. Cette copie comporte une récupération après chaque répétition, y compris la dernière.'}; if(s.date==='2026-10-07')return {...easy(40),id:s.id,date:s.date,week:1,phase:s.phase,corosId:'3',alreadyScheduled:true}; if(s.date==='2026-10-08')return {...s,name:'Repos',kind:'rest',steps:[],declared:0,corosId:'4',deletePlaceholder:true,note:'Supprimer manuellement la fausse séance de 10 min dans COROS. Suppression impossible via MCP.'}; if(s.date==='2026-10-10')return {...s,name:'6 × 10 s · accélérations sur plat',corosId:'5',alreadyScheduled:true,steps:[step(1200,'EF','warmup'),...Array.from({length:6},()=>[step(10,'strides'),step(150,'slow','recovery')]).flat(),step(300,'EF','cooldown')],note:s.note+' Adaptation enregistrée dans COROS le 5 octobre : cible d’allure indicative plutôt que de FC sur 10 secondes. Ne cherche pas à rejoindre brutalement la fourchette.'}; return {...s,corosId:'6',alreadyScheduled:true,steps:[step(1800,'EF'),...Array.from({length:4},()=>[step(300,'42k'),step(180,'recovery','recovery')]).flat(),step(600,'EF','cooldown')],note:'Copie COROS conservée : 72 min calculées, contre 65 min annoncées dans le PDF. Écart visible, sans modification silencieuse.'}})}
function sRPE(minutes,rpe){return minutes*rpe}
function readiness(check,health,hrvBaseline=63){const notes=[];if(!check)return {level:'unknown',title:'Ressenti à renseigner',notes:['Le ressenti et la douleur sont nécessaires avant toute adaptation.']};if(check.pain>=4)return {level:'red',title:'Pas de séance intense',notes:['Douleur déclarée : reporte l’intensité et fais évaluer une douleur persistante.']};if(check.fatigue>=7)notes.push('Fatigue ressentie élevée');if(check.sleep&&check.sleep<6)notes.push('Moins de 6 h de sommeil déclarées');if(health&&health.hrv&&health.hrv<hrvBaseline*0.9)notes.push('HRV en baisse par rapport à la référence');return {level:notes.length>=2?'red':notes.length?'amber':'green',title:notes.length>=2?'Récupération à privilégier':notes.length?'Alléger selon le ressenti':'Pas de signal déclaré',notes:notes.length?notes:['Règle indicative ; elle ne prédit pas les blessures.']}}
function e1rm(kg,reps){return reps>=1&&reps<=12&&kg>0?kg*(1+reps/30):null}
function volume(log){return log.exercises.reduce((sum,e)=>sum+(e.timed?0:e.sets.filter(s=>s.done).reduce((a,s)=>a+s.kg*s.reps,0)),0)}
function toCourse(s,ranges=paces){return {courseName:s.name,courseDescription:s.note||s.source,sportType:1,sections:s.steps.filter(x=>x.meters>0||x.seconds>0).map(x=>({sectionType:{warmup:1,training:2,recovery:3,cooldown:4}[x.type]||2,targetType:x.meters?1:2,targetValue:Math.round(x.meters||x.seconds),intensityType:2,intensityValueStart:ranges[x.zone][0],intensityValueEnd:ranges[x.zone][1]}))}}
const api={START,addDays,pace,time,paces,plan,firstWeekCurrent,duration,distance,sRPE,readiness,e1rm,volume,toCourse};
return api;
})();

export { SportCore };
